version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: note2u-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cup11mouse
      POSTGRES_DB: note2u_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springnet

  app:
    build: .
    container_name: note2u
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - springnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/note2u_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cup11mouse
      SPRING_PROFILES_ACTIVE: dev

volumes:
  pgdata:

networks:
  springnet: